version: '3'  

services: 
  frontend: 
    image: postgres_frontend
    build:
      context: ../part2_5/
      dockerfile: frontend.Dockerfile
    ports: 
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000

  backend: 
    image: postgres_backend
    build:
      context: ../part2_5/
      dockerfile: backend.Dockerfile
    ports: 
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_PASSWORD=example
      - DB_USERNAME=postgres
      - DB_HOST=db
    depends_on:
      - db
      - redis

  redis:
    image: redis
    restart: unless-stopped
    
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: exercise-2-9
